# Generated by Django 3.0.5 on 2020-05-03 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('provider', models.IntegerField()),
                ('has_2g', models.BooleanField()),
                ('has_3g', models.BooleanField()),
                ('has_4g', models.BooleanField()),
            ],
        ),
    ]
